### PR TITLE
feat: command gen

### LINKED ISSUE #788: Binary launcher MVP
- run launcher, specify network (simnet, testnet, mainnet), cli commands: up, down, restart
- mount `C:/users/username/Appdata/Roaming/xud-docker`, backup path is set to this path for MVP too

### PR DESCRIPTION
**Pull request by reliveyy**
This PR implements the `gen` command which will translate the xud-docker configurations into a docker-compose.yml file.

Todos:
- [x] arby
- [x] bitcoind
- [x] boltz
- [x] connext
- [x] geth
- [x] litecoind
- [x] lndbtc
- [x] lndltc
- [x] proxy
- [x] webui
- [x] xud
- [x] call `Apply` function of each service and generate the docker-compose.yml file
- [x] support TOML conf files

EDIT by @kilrau : closes https://github.com/ExchangeUnion/xud-docker/issues/788

### CODE REVIEW

**Comment by ghost** [comment]
I'm getting this output when building this branch and launching:
```
ar@DESKTOP-IEMK9HH MINGW64 ~/xud-launcher (feat/gen)
$ ./xud-launcher -n simnet gen
panic: gen flag redefined: arby.disabled

goroutine 1 [running]:
github.com/spf13/pflag.(*FlagSet).AddFlag(0xc000106200, 0xc00014b400)
        C:/Users/ar/go/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:848 +0x83f
github.com/spf13/pflag.(*FlagSet).VarPF(0xc000106200, 0xeaab40, 0xc00005ace0, 0xc00000b020, 0xd, 0x0, 0x0, 0xc000012e60, 0x1b, 0xc00004b380)
        C:/Users/ar/go/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:831 +0x11f
github.com/spf13/pflag.(*FlagSet).BoolVarP(0xc000106200, 0xc00005ace0, 0xc00000b020, 0xd, 0x0, 0x0, 0x0, 0xc000012e60, 0x1b)
        C:/Users/ar/go/pkg/mod/github.com/spf13/pflag@v1.0.5/bool.go:55 +0x9e
github.com/spf13/pflag.(*FlagSet).BoolVar(...)
        C:/Users/ar/go/pkg/mod/github.com/spf13/pflag@v1.0.5/bool.go:50
github.com/reliveyy/xud-launcher/service.configureCommonFlags(0xe2fc94, 0x4, 0xc00005ace0, 0x1095c40, 0x13, 0x0)
        C:/Users/ar/xud-launcher/service/base.go:14 +0x1ab
github.com/reliveyy/xud-launcher/service.Arby.ConfigureFlags(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        C:/Users/ar/xud-launcher/service/arby.go:39 +0xa5
github.com/reliveyy/xud-launcher/cmd.init.2()
        C:/Users/ar/xud-launcher/cmd/gen.go:64 +0xbca
```

**Comment by ghost** [comment]
@reliveyy is this ready to review again?

**Comment by reliveyy** [comment]
> @reliveyy is this ready to review again?

Not yet.

**Comment by reliveyy** [comment]
The light mode mainnet is partially working for me now. I mean the `xucli create` works only. Things needs to be done or verified:

- [x] connext 500 error on xud side
- [x] proxy "Failed to load /root/config.sh"
- [x] proxy /var/run/docker.sock volume
- [ ] arby test
- [ ] boltz test
- [ ] native windows test

I've applied a simple workaround to avoid "/mnt/hostfs" usage in xud service. I mapped `./backup` to `/root/backup` in xud service. That means the backup location is fixed in "backup" folder inside network dir.

P.S. The steps I created an xud-docker light mode mainnet manually.

```bash
# Generate docker-compose.yml file
./xud-launcher -n mainnet gen --arby.disabled=false

# Start L2 services
./xud-launcher -n mainnet up lndbtc
./xud-launcher -n mainnet up lndltc
./xud-launcher -n mainnet up connext

# Waiting for lnds to be synced and start XUD
./xud-launcher -n mainnet up xud

# Make sure xud got it's wallet created/restored and start optional services
./xud-launcher -n mainnet up arby
./xud-launcher -n mainnet up boltz
./xud-launcher -n mainnet up proxy
```

**Comment by kilrau** [comment]
> connext 500 error on xud side

Not sure if that is related to the launcher, might be a different issue.

**Comment by ghost** [comment]
> connext 500 error on xud side

If you're running master branch of xud-docker then this is expected. V1 is no longer working for simnet. @reliveyy

**Comment by ghost** [comment]
> arby test

I think arby is not required for the MVP of the launcher since the Windows UI does not support it? @reliveyy @kilrau

**Comment by kilrau** [comment]
agreed

**Comment by kilrau** [comment]
What we just agreed: **create flow happens in proxy container**
- change order in launcher: bring up proxy first
- expose create, proxy blocks `create` as new endpoint, which is blocked until lnd light clients are synced
- proxy "Failed to load /root/config.sh"
- make proxy work fully on Windows

**Comment by reliveyy** [comment]
@kilrau It took more than 3 hours as I expected. Current todos are

- [x] test proxy-first PR
- [x] implement `/api/v1/xud/create` and `/api/v1/xud/unlock`
- [x] test `/api/v1/xud/create` (report an error while lnd syncing)
- [x] test `/api/v1/xud/unlock` (report an error while xud has been unlocked already)
- [x] test on Windows with following steps

```sh
./xud-launcher -n mainnet gen --arby.disabled=false
./xud-launcher -n mainnet up -- -d proxy
./xud-launcher -n mainnet up -- -d lndbtc lndltc connext
curl -sk https://localhost:8889/api/v1/status/lndbtc  # Syncing 0.00% (0/0) -> Syncing 100.00% (xxx/xxx)
curl -sk https://localhost:8889/api/v1/status/lndltc  # Syncing 0.00% (0/0) -> Syncing 100.00% (xxx/xxx)
./xud-launcher -n mainnet up -- -d xud
curl -sk https://localhost:8889/api/v1/status/xud  # decide to create or unlock (I will enhance this status with nodekey.dat)
curl -sk -d '{"password": "changeme"}' -H 'Content-Type: application/json' https://localhost:8889/api/v1/xud/create
curl -sk -d '{"password": "changeme"}' -H 'Content-Type: application/json' https://localhost:8889/api/v1/xud/unlock
./xud-launcher -n mainnet up -- -d arby boltz
```

**Comment by krrprr** [comment]
- [x] Boltz container stays in `btc down; ltc down` status.

A hint from Boltz logs:
```
Waiting for litecoin LND macaroon: /root/.lndltc/data/chain/litecoin/mainnet/admin.macaroon
Waiting for bitcoin LND macaroon: /root/.lndbtc/data/chain/bitcoin/mainnet/admin.macaroon
```

**Comment by reliveyy** [comment]
@krrprr

```yaml
  boltz:
    image: exchangeunion/boltz:1.1.1
    environment:
      - NETWORK=mainnet
    volumes:
      - ./data/boltz:/root/.boltz
```
The exported docker-compose.yml boltz has no other volumes. And it must be the reason why admin.macaroon not found. Should be fixed in minutes.

**Review by krrprr — APPROVED** [review]

**Pull request merged**
